import { Button } from "std-widgets.slint";

export component AppWindow inherits Window {
    min-width: 400px;
    min-height: 300px;
    preferred-width: 800px;
    preferred-height: 600px;

    in-out property <string> content;
    out property <int> select-start;
    out property <int> select-end;

    private property <length> cursor-x;
    private property <length> cursor-y;

    area := TouchArea {
        pointer-event(event) => {
            cursor-x = area.mouse-x;
            cursor-y = area.mouse-y;
        }
    }

    scope := FocusScope {
        key-pressed(event) => {
            content += event.text;
            accept
        }

        Rectangle {
            x: cursor-x;
            y: cursor-y;
            width: 1px;
            height: 10px;
            background: red;
        }

        Rectangle {
            x: 0px;
            y: 0px;
            border-color: #822;
            border-width: 1px;
    
            Text {
                x: 0px;
                y: 0px;
                color: #000;
                text: content;
            }
        }
    }
}
