import {
    Button,
    CheckBox,
    ComboBox,
    GroupBox,
    VerticalBox,
    HorizontalBox,
    LineEdit,
    ListView,
    ProgressIndicator,
    ScrollView,
    Slider,
    SpinBox,
    StandardButton
} from "std-widgets.slint";

export component Std1Page inherits Window {
    VerticalLayout {
        Button {
            text: "Click Me";
            clicked => { self.text = "Clicked"; }
        }

        CheckBox {
            width: parent.width;
            min-height: 100px;
            text: "Hello World";
        }

        ComboBox {
            width: parent.width;
            min-height: 100px;
            model: ["first", "second", "third"];
            current-value: "first";
        }

        GroupBox {
            title: "Groceries";
            VerticalBox {
                CheckBox { text: "Bread"; checked: true ;}
                CheckBox { text: "Fruits"; }
            }
        }

        HorizontalBox {
            LineEdit {
                font-size: 14px;
                placeholder-text: "Enter text here";
            }
        }

        ListView {
            width: 150px;
            height: 150px;
            for data in [
                { text: "Blue", color: #0000ff, bg: #eeeeee},
                { text: "Red", color: #ff0000, bg: #eeeeee},
                { text: "Green", color: #00ff00, bg: #eeeeee},
                { text: "Yellow", color: #ffff00, bg: #222222 },
                { text: "Black", color: #000000, bg: #eeeeee },
                { text: "White", color: #ffffff, bg: #222222 },
                { text: "Magenta", color: #ff00ff, bg: #eeeeee },
                { text: "Cyan", color: #00ffff, bg: #222222 },
            ] : Rectangle {
                height: 30px;
                background: data.bg;
                width: parent.width;
                Text {
                    x: 0;
                    text: data.text;
                    color: data.color;
                }
            }
        }

        // 这个样式有点崩坏。
        ProgressIndicator {
            width: parent.width;
            height: 40px;
            progress: 100%;
        }

        // 这东西的子元素要自己锚点。。
        ScrollView {
            width: parent.width;
            height: 200px;
            viewport-width: parent.width;
            viewport-height: 1000px;
            Slider {
                y: 0px;
                width: parent.width;
                height: 100px;
                value: 42;
            }
            SpinBox {
                y: 100px;
                width: parent.width;
                height: 40px;
                value: 42;
            }
            Rectangle { width: 30px; height: 30px; x: 275px; y: 50px; background: blue; }
            Rectangle { width: 30px; height: 30px; x: 175px; y: 130px; background: red; }
            Rectangle { width: 30px; height: 30px; x: 25px; y: 210px; background: yellow; }
            Rectangle { width: 30px; height: 30px; x: 98px; y: 55px; background: orange; }
        }

        VerticalBox {
            StandardButton { kind: ok; }
            StandardButton { kind: apply; }
            StandardButton { kind: cancel; }
        }
    }
}